mybatis:
  mapper-locations: classpath:mapper/**/**Dao.xml
  type-aliases-package: cn.ylw.entity
  configuration:
    jdbc-type-for-null: null
mybatis-plus:
  # mybatis核销配置文件不能与mapper配置文件同一目录
  config-location: classpath:mybatis-config.xml